### ISSUE TITLE
关于框架的几个疑问

### ISSUE THREAD

**Issue by dingjun606** [chubbyjiang/aisql-bigdata-base#3]
您好，之前关于大数据工程项目规范有很多疑问，您这个项目给了我很多帮助，最近尝试试用该项目标准化大数据工程，目前有一下几点疑问想要请教：
>1. 分层的命名感觉有点奇怪，比如业务计算逻辑模块直接叫api，让熟悉web项目分层的人很难接受，请问这种命名方式的初衷是什么？
>2. service层读取hive表的接口：
>    * 是否可以放弃一些灵活性，限制col和where必须是bean中定义的字段，这样字段名可以做静态校验，减少字段名拼写问题？
>    * select后，是否可以根据传入的col名动态改变返回类的字段，防止访问到空字段?
>3. 该项目是否有后续规划？

**Comment by xiaohei-info** [comment]
> 您好，之前关于大数据工程项目规范有很多疑问，您这个项目给了我很多帮助，最近尝试试用该项目标准化大数据工程，目前有一下几点疑问想要请教：
> 
> > 1. 分层的命名感觉有点奇怪，比如业务计算逻辑模块直接叫api，让熟悉web项目分层的人很难接受，请问这种命名方式的初衷是什么？
> > 2. service层读取hive表的接口：
> >    
> >    * 是否可以放弃一些灵活性，限制col和where必须是bean中定义的字段，这样字段名可以做静态校验，减少字段名拼写问题？
> >    * select后，是否可以根据传入的col名动态改变返回类的字段，防止访问到空字段?
> > 3. 该项目是否有后续规划？

1.关于分层命名的规范，对于熟悉web项目的人确实有点奇怪，这个没什么特殊的含义，就是当初内部对齐的命名，所以不必纠结哈。
2.你提到的两个问题都可以实现。
3.工作变动，目前暂时没有太多时间和场景继续完善下去，这个项目本身也有半年没更新了，可以基于这个项目或者参考一下去做自己内部的框架。
